### ISSUE TITLE
Language chooser should collapse when clicking outside or after choosing language

### ISSUE THREAD

**Issue by AbelLykens** [storingbitcoin-info/website#12]
**What could be better**
If you choose a language I want the menu to close

** On what page are you experiencing this problem **
everywhere

**Additional context**
I do not know how to fix this myself

**Comment by ArtemSilka** [comment]
Hey @AbelLykens , I would like to take on this issue.

**Comment by AbelLykens** [comment]
That is great! Please do. What I want is these 2 situation:

* Click the chooser. Language menu is shown. I click the language I want. Language changes and menu disappears
* Click the chooser. Language menu is shown. I decide I do not want to change the language, and click outside of the menu. Menu disappears

Hope it makes sense :)

**Comment by StijnBTC** [comment]
@ArtemSilka make sure that you look at PR #15 before fixing this, the language chooser is changed a bit.

**Comment by ArtemSilka** [comment]
@AbelLykens  Thank you. Will update you soon. 
@StijnToemen, Thank you for letting me know. Is `main` branch up to date?

**Comment by ArtemSilka** [comment]
Hey @AbelLykens , sorry but could not figure the whole thing, bit lost in the function logic. Managed to close it when select languages or click outside but now when clicking on the flags, it'll open up too. 
Sorry that cannot help here

**Comment by StijnBTC** [comment]
Opened PR #21 with fix.

**Comment by AbelLykens** [comment]
Thanks #21 fixed it!
