### ISSUE TITLE
Number each screen 

### ISSUE THREAD

**Issue by harm-h** [storingbitcoin-info/website#14]
The website guides the user through a graph of options. In order to discuss whats on a certain screen, I'd suggest to number each step. 
Maybe something like
   S1
   S2
   S2.1
   S2.2   (depending on what path the user took)
The "S" stands for both Screen and Step.    
[A further refinement could be to have different letters, like Q.. for pages that contain only questions-to-be-answered and A.. for answers, pages with instruction or information.  (But the letter i is not well suited me thinks, this is i-eleven: I11, confusing).  But too complex for now]

"Hey, there's a typo on S218, 'the' is spelled as 'teh'"
could be a typical reaction/tweet once this scheme is implemented.

**Comment by AbelLykens** [comment]
I see what you mean. I think there might (already) be a solution:

All screens have an ID, like `start` and `hardwarewallet`:

https://storingbitcoin.info/#/start
https://storingbitcoin.info/#/hardwarewallet

I think we can use those to refer to specific pages (in issues).

I would not like to use numbers, as the steps change in the future, and that could break the (previously linked-to) links.

Please reopen if I am incorrect :+1: . Thanks for thinking with us/the project.
