### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by AbelLykens** [storingbitcoin-info/website#2]
theme/bitcoin.css
styling in bitcoin colors?

**Comment by AbelLykens** [comment]
Menubar needs some styling (these `<a href`s are ugly!). Also overall I think we could use some more bitcoin orange.

**Comment by harm-h** [comment]
The links (choices) should look like buttons, not underlined text. 

https://css-tricks.com/css-basics-styling-links-like-boss/#links-as-buttons

**Comment by harm-h** [comment]
> (these `<a href`s are ugly!). 


The links (choices) should look like buttons, not underlined text.

https://css-tricks.com/css-basics-styling-links-like-boss/#links-as-buttons

**Comment by AbelLykens** [comment]
Thanks for the PR Stijn. Opened #17 and #18 for specific questions/enhancements!
