### ISSUE TITLE
Text issue at /#/buywallet

### ISSUE THREAD

**Issue by StijnBTC** [storingbitcoin-info/website#25]
**What could be better**
There are three options, all with the same text but with different link destinations.

**On what page are you experiencing this problem**
https://storingbitcoin.info/#/buywallet

**Additional context**
In both Dutch and English.

**Comment by AbelLykens** [comment]
Fixed I think now

**Comment by AbelLykens** [comment]
81dc53f1c961cebeb895e5700e28b76bdc993bac

**Comment by AbelLykens** [comment]
Thanks for noticing
