### ISSUE TITLE
Infobox for extra info

### ISSUE THREAD

**Issue by Dan-Xi** [storingbitcoin-info/website#29]
Ik vermoed dat er meer uitleg nodig is voor pre/new-coiners dan enkel de vragen dan tekst. 
Ik zou graag zien dat je bij bepaalde termen meer info kan opvragen. Bijvoorbeeld definitie / uitleg over de term of een verwijzing naar een video/site waar je meer uitleg kan vinden. Misschien is het een idee om dit middels een mouse-over bij definities te doen. Uitgebreidere zaken via een 'lees meer over...' die in een nieuw tabblad opent.

**Comment by AbelLykens** [comment]
Klinkt goed. Volgens mij moet het een soort popup worden? Zijn daar plugins voor of kan dat met kale CSS? Enig idee @StijnToemen ?

**Comment by AbelLykens** [comment]
(Changed title to EN)

**Comment by AbelLykens** [comment]
Code implemented
