### ISSUE TITLE
UX/UI: Warning explanation 

### ISSUE THREAD

**Issue by hasbonk** [storingbitcoin-info/website#37]
**Is your request related to a problem? Please describe.**
To describe the warnings add a little warning component instead of underlining it.

**Describe the solution you'd like**
<img width="826" alt="Screenshot 2020-12-28 at 20 01 50" src="https://user-images.githubusercontent.com/3482940/103237323-8e124600-4947-11eb-9928-a6a986780f16.png">
 want to happen.

**Additional context**
https://www.figma.com/file/HZQj1jCxYgHuOm7uKPPkSo/SB?node-id=0%3A1

**Comment by AbelLykens** [comment]
Can we close this? Great input. 
If we want to add more text, we should do it in the warning (please make separate issues for specific unclear warnings :100: )
