### ISSUE TITLE
Infobox translation doesn't work

### ISSUE THREAD

**Issue by StijnBTC** [storingbitcoin-info/website#40]
**What could be better**
When adding the infobox the translation stops working.
example:
*Works:*
`<div> <p class="intro" data-i18n="infobox-header">text to be translated</p></div>`
*Works:*
`<div class="intro"> <p class="intro" data-i18n="infobox-header">text to be translated</p></div>`
*Does not work:*
`<div class="infobox"> <p class="intro" data-i18n="infobox-header">text to be translated</p></div>`

**On what page are you experiencing this problem**
All pages with infobox
- /fundlike 
- /node
- /buywallet
- /multisig

**Additional context**

**Comment by AbelLykens** [comment]
Interesting!

```
        <section id="fundlike">
          <!-- FUNDLIKE -->
          <div class="infobox">
            <p class="header" data-i18n="infobox-header">Samples of funds are:</p>
            <ul>
              <li><a href="https://grayscale.co/bitcoin-trust/" rel="noopener noreferrer" target="_blank">Grayscale Bitcoin Trust</a></li>
              <li><a href="https://www.vaneck.com/nl/en/etf/digital-assets/vbtc/fact-sheet/" rel="noopener noreferrer" target="_blank">VanEck Vectors Bitcoin ETN</a></li>
            </ul>
          </div><!--/infobox-->
          <p class="intro" data-i18n="intro">There are funds (ETNs) you can buy on regular exchanges, the same type of exchange you can but stocks. Click the i-icon above for more info.</p>
          <p class="warning" data-i18n="warning"><img src="assets/img/Warning.svg">If you use these products, you can never be technically sure the fund really holds your bitcoin.</p>
          <p class="question" data-i18n="question">How does that sound?</p>
          <ul class="button">
            <li><a href="#/amount" data-i18n="reconsider">Don't like that. I want to self-custody.</a></li>
            <li><a href="#/opsec" data-i18n="theend">Sure! I will buy fund-like products on a regular exchange.</a></li>
          </ul>
        </section><!-- /FUNDLIKE -->
```
Intro gets translated. infobox-header (the `<p>` in the `<div>`) does not. @Martinomagnifico do you maybe know why? :)

**Comment by StijnBTC** [comment]
I think it is because the infobox class contains `display:none; ` when I remove `display:none` it does work

**Comment by AbelLykens** [comment]
That is weird right? It only translates visible stuff? :thinking_face:

**Comment by StijnBTC** [comment]
Nope forget that. It has to do with how we set the infobox content, the translation is done on the initial page load, or when the language changes. 
If the selected language is English, the HTML is rendered as English. When we go to the next slide, a javascript function loads the current HTML and puts it into the infobox. If the language changes, the slide HTML changes too, but the infobox HTML doesn't change because it is outside of an `<section>`. I think I have a workaround for this!

**Comment by AbelLykens** [comment]
Oh yeah! We copy the innerhtml to an other div! Nice find, wonder what you come up with to fix.

**Comment by AbelLykens** [comment]
Nice find and fix
