### ISSUE TITLE
Wallet Recommendations 

### ISSUE THREAD

**Issue by 6102bitcoin** [storingbitcoin-info/website#45]
**What could be better**
Wallet recommendation is to go to bitcoin.org. This list of wallets only includes those where 'The identity of CEOs and/or developers is public' [Source](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)

As such, great wallets like Samourai Wallet (in my opinion the best wallet on Android) are not eligible for listing. 

I suggest recommending wallets, for example Blue Wallet on iOS, Samourai Wallet on Android, Bitcoin Core + Specter wallet on desktop. This is what we have done on [bitcoin-intro.com](https://bitcoin-intro.com). Alternately you could link to [bitcoin-only.com/wallets](https://bitcoin-only.com/wallets)

**On what page are you experiencing this problem**
softwarewallet2

**Comment by AbelLykens** [comment]
Let's use 016a74079bf4074044e33dccb21526a4d961b4ad for now, good list. Bitcoin-intro is quite a lot of new information for new users. Good notes on bitcoin.org (I also think that list is not maintained a lot?)

**Comment by 6102bitcoin** [comment]
Great - Thanks
