### ISSUE TITLE
ssss

### ISSUE THREAD

**Issue by 6102bitcoin** [storingbitcoin-info/website#46]
**What could be better**
SSSS is a complex method of seed splitting and recovery, and requires a computer to split / recombine the shards. If used with a hardware wallet this adds significantly more attack surface. 

Splitting a 24 word seed into 3 partial lists, any two of which can be recombined is likely to be sufficiently secure for most people and eliminates this complexity. 

**On what page are you experiencing this problem**
Issss

**Comment by 6102bitcoin** [comment]
Update: Found the simple option. 

I suggest that the simple option be replaced with the three partial lists method as explained here (from bitcoin-intro.com/en/backup)

```
If you split 24 seed words into 3 partial lists, you can recover the full list of ordered seed words with only 2 of the 3 partial lists, giving some redundancy.


| Seed Words    | List A    | List B    | List C    | 
| ---           | ---       | ---       | ---       |
| 1 - 8         | X         |           |  X        |
| 9 - 16        | X         | X         |           |
| 17 - 24       |           | X         |  X        |

This method is simple and can be done manually (unlike Shamir's Secret Sharing which requires code) but unlike SSS a partial list may be vulnerable to brute force attacks.

The relationship between number of revealed seed words and security against brute force attack is not linear, and it is possible to brute force 4 / 12 words (whereas it we do not believe that it is likely that someone will brute force 8 / 24 seed words).  

For this reason we only recommend doing this with a 24 word seed. 
Ensure you number each seed word to make recovering the list easier
```

**Comment by AbelLykens** [comment]
`ssss` page already linked to the `cutseed` page, but that just had info on cutting in 2 simple parts. Commit 36be45c now adds text and a link to the partial list strategy :heavy_check_mark: .
